export const destinations = [
  {
    slug: 'cancun-riviera-maya',
    name: 'Cancun & Riviera Maya',
    country: 'Mexico',
    tagline: 'The Caribbean Classic',
    description: 'The undisputed favourite for Canadian Indian couples. World-class resort infrastructure, turquoise waters, and a vendor ecosystem built for large South Asian celebrations.',
    image: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800&h=600&fit=crop',
    highlights: ['Direct flights from Toronto, Vancouver, Calgary', 'Mandap-ready beachfront venues', 'Experienced Indian wedding vendors', 'No guest visa required (Canadian passport)'],
    budget: '$80K–$250K CAD',
    bestFor: '100–250 guests',
    season: 'November–April',
    flag: '🇲🇽',
  },
  {
    slug: 'punta-cana',
    name: 'Punta Cana',
    country: 'Dominican Republic',
    tagline: 'Secluded Luxury',
    description: 'Ultra-luxury resorts with Renaissance-era architecture, private beaches, and an intimate atmosphere perfect for exclusive Indian celebrations.',
    image: 'https://images.unsplash.com/photo-1548574505-5e239809ee19?w=800&h=600&fit=crop',
    highlights: ['Ultra-luxury resort venues', 'Private beach ceremony spaces', 'All-inclusive flexibility', 'Excellent photography backdrops'],
    budget: '$70K–$200K CAD',
    bestFor: '75–175 guests',
    season: 'December–May',
    flag: '🇩🇴',
  },
  {
    slug: 'jamaica',
    name: 'Jamaica',
    country: 'Jamaica',
    tagline: 'Vibrant & Intimate',
    description: 'Lush tropical settings, reggae warmth, and boutique luxury resorts that offer an intimate, personalized alternative to large-resort destinations.',
    image: 'https://images.unsplash.com/photo-1559494007-9f5847c49d94?w=800&h=600&fit=crop',
    highlights: ['Boutique luxury venues', 'Lush tropical backdrops', 'Warm, personalized service', 'Great for smaller celebrations'],
    budget: '$60K–$150K CAD',
    bestFor: '50–120 guests',
    season: 'December–April',
    flag: '🇯🇲',
  },
  {
    slug: 'italy',
    name: 'Italy',
    country: 'Italy',
    tagline: 'Old World Grandeur',
    description: 'Amalfi Coast cliffs, Tuscan vineyards, Lake Como villas — Italy offers the most breathtaking backdrops on earth for a truly landmark Indian wedding.',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=800&h=600&fit=crop',
    highlights: ['Iconic UNESCO heritage venues', 'Amalfi, Lake Como, Tuscany options', 'Exceptional fine dining', 'High-fashion photography'],
    budget: '$150K–$500K CAD',
    bestFor: '50–150 guests',
    season: 'May–October',
    flag: '🇮🇹',
  },
  {
    slug: 'dubai',
    name: 'Dubai',
    country: 'UAE',
    tagline: 'Ultra-Modern Opulence',
    description: 'Skyscrapers, desert landscapes, and seven-star hospitality. Dubai offers a culturally familiar setting for South Asian families with unmatched luxury infrastructure.',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop',
    highlights: ['Culturally familiar for South Asian families', 'No alcohol restrictions at licensed venues', 'Direct flights from all Canadian cities', 'World-class luxury hotels'],
    budget: '$100K–$400K CAD',
    bestFor: '100–300 guests',
    season: 'October–March',
    flag: '🇦🇪',
  },
  {
    slug: 'thailand',
    name: 'Thailand',
    country: 'Thailand',
    tagline: 'Exotic & Breathtaking',
    description: 'Phuket and Koh Samui offer dramatic tropical scenery, world-class hospitality, and extraordinary value for large Indian wedding celebrations.',
    image: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&h=600&fit=crop',
    highlights: ['Stunning tropical venues', 'Excellent value at luxury tier', 'Experienced Indian wedding vendors in Phuket', 'Spectacular photography'],
    budget: '$60K–$200K CAD',
    bestFor: '75–200 guests',
    season: 'November–April',
    flag: '🇹🇭',
  },
];
